# Generated by Django 5.0.4 on 2024-04-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idr_idm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breakdown',
            new_name='BreakdownIdrIdm',
        ),
    ]
