# Generated by Django 5.0.4 on 2024-04-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idr_idm', '0002_rename_breakdown_breakdownidridm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='MachineIdrIdm',
        ),
    ]
