# Generated by Django 5.0.4 on 2024-04-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idr_idm', '0003_rename_machine_machineidridm'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownidridm',
            name='km_enter',
            field=models.FloatField(blank=True, null=True, verbose_name='Km/h Entrer'),
        ),
        migrations.AddField(
            model_name='breakdownidridm',
            name='km_exit',
            field=models.FloatField(blank=True, null=True, verbose_name='Kùm:h Sortie'),
        ),
    ]
