# Generated by Django 5.0.4 on 2024-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idr_colas', '0002_alter_breakdownidrcolas_jde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownidrcolas',
            name='jde',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
