# Generated by Django 5.0.4 on 2024-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level_1',
            field=models.BooleanField(default=False, help_text='Action ID Motors'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level_2',
            field=models.BooleanField(default=False, help_text='Action SAV ID Rental'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level_3',
            field=models.BooleanField(default=False, help_text='Action Import Export ID Motors'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level_4',
            field=models.BooleanField(default=False, help_text='Action Direction'),
        ),
    ]
