# Generated by Django 5.0.4 on 2024-04-20 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acteur', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('add', 'Ajout'), ('update', 'Modification'), ('delete', 'Delete')], default='add', max_length=100)),
                ('argument', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jointe',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='media/')),
                ('acteur', models.CharField(blank=True, editable=False, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('locality', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['commune', 'locality'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.localisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Start Breakdown')),
                ('appointment', models.DateTimeField(blank=True, null=True, verbose_name='Request Appointment')),
                ('enter', models.DateTimeField(blank=True, null=True, verbose_name='Enter Garage')),
                ('leave', models.DateTimeField(blank=True, null=True, verbose_name='Leave Garage')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order Repair')),
                ('archived', models.BooleanField(default=False)),
                ('works', models.TextField(blank=True, null=True, verbose_name='Work Request')),
                ('prevision', models.TextField(blank=True, null=True, verbose_name='Exit Garage Prevision')),
                ('piece', models.TextField(blank=True, null=True, verbose_name='Etat Piece')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Decision')),
                ('diagnostics', models.TextField(blank=True, null=True, verbose_name='Diagnostics & Commentaire SAV')),
                ('achats', models.TextField(blank=True, null=True, verbose_name='Commentaire Achats')),
                ('imports', models.TextField(blank=True, null=True, verbose_name='Commentaire Import')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.client')),
                ('historic', models.ManyToManyField(blank=True, to='apps.historic', verbose_name='Historique Breakdown')),
                ('jointe', models.ManyToManyField(blank=True, to='apps.jointe', verbose_name='Piece Jointe')),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.localisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matriculate', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=150)),
                ('breakdown', models.ManyToManyField(blank=True, to='apps.breakdown')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
