# Generated by Django 5.0.4 on 2024-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='leave',
            field=models.DateField(blank=True, null=True, verbose_name='Leave Garage'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='works',
            field=models.TextField(blank=True, null=True, verbose_name='Work Request'),
        ),
    ]
