# Generated by Django 5.0.4 on 2024-04-19 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_machine_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jointe',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='breakdown',
            name='jointe',
            field=models.ManyToManyField(null=True, to='apps.jointe', verbose_name='Piece Jointe'),
        ),
    ]
