# Generated by Django 5.0.4 on 2024-04-15 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_breakdown_leave_breakdown_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('locality', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['commune', 'locality'],
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.RemoveField(
            model_name='breakdown',
            name='location',
        ),
        migrations.AddField(
            model_name='breakdown',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.localisation'),
        ),
        migrations.AddField(
            model_name='client',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.localisation'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
