# Generated by Django 5.0.4 on 2024-04-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_societe_machine_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='name',
            new_name='matriculate',
        ),
    ]
