# Generated by Django 5.0.4 on 2024-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_localisation_remove_client_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
