# Generated by Django 5.0.4 on 2024-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_jointe_breakdown_jointe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='jointe',
            field=models.ManyToManyField(blank=True, to='apps.jointe', verbose_name='Piece Jointe'),
        ),
    ]
