# Generated by Django 5.0.4 on 2024-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_localisation_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
