# Generated by Django 5.0.4 on 2024-04-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_breakdown_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='end',
        ),
        migrations.RemoveField(
            model_name='breakdown',
            name='exit',
        ),
        migrations.AddField(
            model_name='breakdown',
            name='achats',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire Achats'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='decision',
            field=models.TextField(blank=True, null=True, verbose_name='Decision'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='diagnostics',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnostics & Commentaire SAV'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='imports',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire Import'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='piece',
            field=models.TextField(blank=True, null=True, verbose_name='Etat Piece'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='prevision',
            field=models.TextField(blank=True, null=True, verbose_name='Exit Garage Prevision'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Request Appointment'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='enter',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enter Garage'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='leave',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Leave Garage'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start Breakdown'),
        ),
    ]
