# Generated by Django 5.0.4 on 2024-04-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_breakdown_end_remove_breakdown_exit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Breakdown'),
        ),
    ]
